### ISSUE TITLE
What are your favorite redirects?

### ISSUE THREAD

**Issue by zeke** [requestly/requestly-issues#1]
Hi @sachinjain024. Thanks for creating this powerful extension. I just discovered it.

To better understand some possible uses of it, would you be willing to share some example rules, or even better: your exported list of rules? I am trying to imagine the various interesting ways this thing can be used. :)

Thanks, and keep up the good work.

:v:

**Comment by sachinjain024** [comment]
@zeke Thanks for asking this question! I usually get very users who try to explore the possibilities with Requestly. Others just seem to be happy after solving their particular use cases So I am really glad you asked this.

I can give you an idea how it can be used in various scenarios. I had the rules for them but its bit of difficult for me to find them out. Once you get an idea of rule creation, you should be able to form your own rules.

Here are the use cases I have used my self and often see people using for it.
1. URL shortcuts (Redirect Rule)

> Source Url Matches /q=rgi/gi
> Destination https://github.com/requestly/requestly-issues

Above url will match your search in google chrome addressbar and you just need to type rgi and it will take you to destination url. Similarly, you can create your own shortcuts.

2. Debug JS running in production

Often we find some bug in js code running in production sites. People then try to reproduce the issue in local environment, fix in local environment and then deploy. Requestly offers a better alternative. Since you know the culprit JS code throwing error (or causing issue), you can setup requestly Redirect/Replace rule like this:

> Source Url Contains amazon.com/bin/ga-min.js
> Destination http://localhost:7070/ga.js

Now, you can make your changes, fix the issue and deploy more confidently. You need not reproduce the issue on local environment.

3. Modify Query Parameters (Replace Rule)

> Replace ?dl=0 with ?dl=1
> When Source Url contains dropbox.com

It helps you download dropbox files instead of opening them in your browser. Helpful when you want to host your JS files on dropbox.

This is an example of modifying query params. You can modify query params as per your use case.

You can read this article which I planned to published somewhere on web (https://github.com/codebrackets/codebrackets.github.io/tree/master/articles/01-http-request-debugging) but could not do so. Neither smashing magazine or codetuts accepted this :-( So I just left this as it is.

Another interesting use case is to download youtube videos.

5. Download Youtube Videos (Redirect Rule)

> Source Url Matches (Regex) *youtube.com*dl=1
> Destination: http://keepvid.com/?url=$1youtube.com$2

6. Amazon smile

Replace www.amazon.com with smile.amazon.com. Other users have used this but I don't know the exact rule for this.

I can go on and on. I hope you get the adsense. Thanks once again for asking this.

**Comment by sachinjain024** [comment]
@zeke Did I answer your question ? Let me know if you have any specific questions. I'd be glad to answer them.

**Comment by zeke** [comment]
Yeah this is awesome. Sorry for not responding. Maybe you should put this stuff in the readme or the extension page for others to discover!

**Comment by sachinjain024** [comment]
@zeke Thanks for suggestion! I will publish this content soon on http://requestly.in/content/articles/
