### ISSUE TITLE
Modify headers does not seem to work anymore

### ISSUE THREAD

**Issue by johan-gorter** [requestly/requestly-issues#19]
I have a rule:
```
Remove Response Header x-frame-options
Source Host Equals www.google.com
```

However, the response header still appears when I open www.google.com

**Comment by sachinjain024** [comment]
@johan-gorter Modification of header works! Unfortunately modification in response headers are not visible in chrome dev tools. This is due to chromium bug/pending feature. 

Read this ticket for more details: https://bugs.chromium.org/p/chromium/issues/detail?id=258064

It should be working. Its just not visible to you.

**Comment by johan-gorter** [comment]
Thanks for the info, I found my real bug now.
