### ISSUE TITLE
Can't modify response header

### ISSUE THREAD

**Issue by wufeifei** [requestly/requestly-issues#9]

**Comment by sachinjain024** [comment]
@wufeifei Just in case you are looking for modifications with Chrome dev tools, there is a bug in chrome dev tools due to which modifications is not visible. However, your modification should work if your filter criteria is correct.

If that is not the case, Please provide me other details so that I can look into it.

**Comment by wufeifei** [comment]
Chrome Version: 57.0.2987.110 (64-bit)
OS Version: macOS 10.12.3

Request header can be added, modified and deleted, but the response header not work (also tried to set the url match, but also does not work).

Can you reproduce it on your computer?

![2017-03-24_10-18-34](https://cloud.githubusercontent.com/assets/1611552/24277944/91367f44-107b-11e7-8c6a-2a9702424554.png)
![2017-03-24_10-18-45](https://cloud.githubusercontent.com/assets/1611552/24277946/956d6ae6-107b-11e7-9f35-f89674215a6c.png)

**Comment by sachinjain024** [comment]
@wufeifei This is what I was talking about. Modification happens for response headers but is not visible in dev tools. This is chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=258064

You can see all modifications for request headers in Dev tools but not for response headers.

**Comment by wufeifei** [comment]
@sachinjain024 Solved, thank you very much!
